---
title: "PA1_template.Rmd"
author: "sravani kaza"
date: "3/13/2020"
output: html_document
---
```{r}
if(!file.exists('activity.csv')){
  unzip('activity.zip')
}
DF <- read.csv('activity.csv')
str(DF)
```
```{r}
# Create the sums of steps per date
DFsteps <- tapply(DF$steps, DF$date, FUN=sum, na.rm=TRUE)

# Perform histogram of steps per day
library(ggplot2)
qplot(DFsteps, binwidth=1000, xlab="total number of steps taken each day")
```
```{r }
stepsMean <- mean(DFsteps, na.rm=TRUE)
stepsMedian <- median(DFsteps, na.rm=TRUE)

# Output mean and median
stepsMean
```
```{r}
stepsMedian
```

```{r}
library(ggplot2)

# Create the means by intervals
averages <- aggregate(x=list(steps=DF$steps), by=list(interval=DF$interval),FUN=mean, na.rm=TRUE)

ggplot(data=averages, aes(x=interval, y=steps)) +
  geom_line() +
  ggtitle("Time Series: average number of steps") +
  xlab("5-minute interval") +
  ylab("average number of steps taken")
```
```{r}
averages[which.max(averages$steps),]
```
```{r}
# copy of data frame
DF2 <- DF

# add column for copleating index
DF2$CI <- "original"

# number of rows to check
l <- nrow(DF2)

# numbers of NAs
length(which(is.na(DF2$steps)))
```
```{r}
# replace NAs by corresponing mean of the same interval --> complete data frame DF2
for (i in 1:l) {
  if (is.na(DF2[i,1])) {
    DF2[i,1] <- averages[averages$interval == DF2[i,3],2]
    DF2[i,4] <- "completed"
  }
}

# numbers of NAs / completed (control)
length(which(is.na(DF2$steps)))
```
```{r}
length(which(DF2$CI=="completed"))
```
```{r}
# Recreate the sums of steps per date
DFsteps2 <- tapply(DF2$steps, DF2$date, FUN=sum, na.rm=TRUE )

# Recreate the mean and median of steps per date
stepsMean2 <- mean(DFsteps2)
stepsMedian2 <- median(DFsteps2)

c(stepsMean2, stepsMean)
```
```{r}
c(stepsMedian2, stepsMedian)
```
```{r}
# Preparation environment
library(ggplot2)
library(gridExtra)
require(gridExtra)

# Perform histogram of steps per day
plot1 <- qplot(DFsteps, 
               binwidth=1000, 
               ylim=c(0,15),
               main="original", 
               xlab="total number of steps taken each day")

plot2 <- qplot(DFsteps2, 
               binwidth=1000, 
               ylim=c(0,15),
               main="completed", 
               xlab="total number of steps taken each day")

# Plotting 2 plot in grid
grid.arrange(plot1, plot2, ncol=2)
```





